name: "Verilog Tests"

on:
    push:
      branches: [main]
      paths:
        - "**.v"
        - ".github/workflows/ci.yml"
    pull_request:
      branches: [main]
      paths:
        - "**.v"
        - ".github/workflows/ci.yml"
    release:
      types: [created]
    schedule:
      - cron: "0 0 * * 0"

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v4

    - name: "Install iverilog"
      run: |
        sudo apt-get update
        sudo apt-get install iverilog

    - name: "Run test target"
      run: |
        make test
